services:
  react-frontend:
    build: react-frontend
    restart: always
    volumes:
      - ./react-frontend:/app
      - /app/node_modules # prevent local node_modules from overriding container's
    ports:
      - 5173:5173
  sails-api:
    build: sails-api
    restart: always
    command: npm run dev
    volumes:
      - ./sails-api:/app
    environment:
      PORT: 8080
      NODE_ENV: development
      FEATHERS_LOGS_URL: ${FEATHERS_LOGS_URL}
      FEATHERS_USERS_URL: ${FEATHERS_USERS_URL}
    ports:
      - 8080:8080
  feathers-logs-service:
    build: feathers-logs-service
    command: npm run dev
    volumes:
      - ./feathers-logs-service:/app
    environment:
      PORT: 8081
      NODE_ENV: development
      MONGODB: ${MONGODB_URL}
      FEATHERS_SECRET: ${APP_JWT_SECRET}
    depends_on:
      - mongo
    restart: always
  feathers-users-service:
    build: feathers-users-service
    command: npm run dev
    volumes:
      - ./feathers-users-service:/app
    environment:
      PORT: 8082
      NODE_ENV: development
      MONGODB: ${MONGODB_URL}
      FEATHERS_SECRET: ${APP_JWT_SECRET}
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:8.0.10
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:1.0.0-alpha
    depends_on:
      - mongo
    restart: always
    ports:
      - 8088:8081
